before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: RA6ccgh1cqTM7A+zgVuukInuAnvbSO+nxvCvN3vOe+qq0SmiNfPVAhxZWIJcTBPsUoI5SQa/8Fz9yzFrvAQCXuAX4FMfZvxhXvS4WsBRgjn8pcdUgEiZt+t/eFD3C4ltWVR9Ek4jZhEXLLMoEoH2sCFMHNtHliIeKelP9sGZuNAofF4JHCWDLOnTu5m6S0tbCBfIiANdm8x73k718bN2Fb0qLtNIXy2hSwQ98CUydhRNFzv1jVtmJYyTIUwHnDUCvBxDHdX4B2vD0v1ak9nARpcw1vYNUnoTBHpj5p2n0Ap+lA5wVRUydv+8TTMM3vMd3bqrfabcPHu2KeKw89ISsnIYedDgPX7yjxBhW0ielzUDWxumZVxzY1P7/LLwyB0aELbz49br5ZFz2D5DU5s7gnJTvFaAAidQ0TbYBIIp8P/TxTNVsCG7HlWeqT37sssxTYfO688/3uXR35k2/j8dRSYcLCcB4ja9rbO307mI5FQppHqanSWXI6fdMNJWuqv67cPOKwWKfaI/yIxr0FjvkTCrrfcz32H+RDCcyZILLBgbSj58H8bJYhL4dLya5SZ5nejkLmz6VbhwrZ8m6zSMl5V/hZ+Tafiklqt2Ww4x5HSxAdVqUfze7MQIryCO64hya2a6bXuQuMJzLPLOpzRmg0y10H5SLKlj/UmXNltpBJY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
